name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    strategy:
      matrix:
        node:
          - 14

    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        id: node

      - run: yarn install
      - run: yarn test --coverage

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
